name: Almacenamiento de datos
run-name: Guardando datos
on: 
  workflow_dispatch:
jobs:
  Guardando datos:
    runs-on: ubuntu-latest
    steps:
      - name: Utilizando un secret
        env:
          creando_secret: ${{ secrets.EJEMPLO_DE_UN_SECRET}}
        run: example-comand "$creando_secret"