name: Contextos
run-name: New Contextos
on: 
  push:
    branches:
      - main
jobs:
  Trabajo-De-Contexto:
    runs-on: ubuntu-latest
    steps:
      - name: Numero Aleatorio entre 0 y 1
        id: genera_numero
        run: echo "::set-output name=numero_aleatorio::$((RANDOM % 2))"
      - name: Paso o Fallo
        run: |
          source $GITHUB_ENV
          if [[ ${{ steps.genera_numero.output.numero_aleatorio }} == 0 ]]; then exit 0; else exit 1; fi