name: Hola Mundo

on: push

jobs:
  first_job:
    name: My first workflow
      runs-on: ubuntu-latest
      steps:
          uses: actions/checkout@v4
          uses: actions/setup-nodenv@v3
        - name: Run Code
          run: node hola_mundo.js