name: Nuevo Expresiones
on:
  workflow_dispatch:
    input:
      palabra:
        descripcion: Palabra a cambiar
        require: true
        type: string
      cambio1:
        descripcion: parte 1 a cambiar
        require: false
        type: string
      cambio2:
        descripcion: parte 2 a cambiar
        require: false
        type: string
      cambio3:
        descripcion: parte 3 a cambiar
        require: false
        type: string
      cambio4:
        descripcion: parte 4 a cambiar
        require: false
        type: string
jobs:
  first:
    if: ${{ github.input.cambio1 == '*'}}
    runs-on: ubuntu-latest
    steps:
    - name: Cambio de primer palabra
      run: format('{{github.input.palabra {0}', '{{github.input.cambio1}}')
  Second:
    if: ${{ github.input.cambio2 == '*' }}
    runs-on: ubuntu-latest
    steps:
    - name: Cambio de segunda palabra
      run: format('{{github.input.palabra {0}', '{{github.input.cambio2}}')
  Third:
    if: ${{ github.input.cambio3 == '*' }}
    runs-on: ubuntu-latest
    steps:
    - name: Cambio de tercer palabra
      run: format('{{github.input.palabra {0}', '{{github.input.cambio3}}')
  Fourth:
    if: ${{ github.input.cambio4 == '*' }}
    runs-on: ubuntu-latest
    steps:
    - name: Cambio de cuarta palabra
      run: format('{{github.input.palabra {0}', {{github.input.cambio4}}')